apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: suf8gui83-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: suf8gui83-go 
  name: suf8gui83-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: suf8gui83-go 
