apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: suf8gui83-go-gitops
  description: This is GitOps manifest for suf8gui83-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=suf8gui83-go
    backstage.io/kubernetes-id: suf8gui83-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: suf8gui83-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:suf8gui83-go
